module("main.py", base_path="src/")
module("app.py", base_path="src/")
module("doc.py", base_path="src/")
module("font_generator.py", base_path="src/")
module("lcdFont.py", base_path="src/")
module("lcd.py", base_path="src/")
module("rtc.py", base_path="src/")
